### ISSUE TITLE
File trees_length.py is missing

### ISSUE THREAD

**Issue by milag6** [roblanf/SRHtests#8]
Hi
I was fallowing the Read me file but I couldnt find the file: 9. run python trees_lengths.py
Was it deleted?
Thanks

**Comment by roblanf** [comment]
Hi @milag6, 

Sorry for the oversight on our part!

@suhanaser do you have that script? If so can you upload it. 

Rob

**Comment by suhanaser** [comment]
Missing file has been uploaded

**Comment by roblanf** [comment]
Fixed here: 
https://github.com/roblanf/SRHtests/commit/e7592e0116d68ce213bee30c4f177eb7b76093de

Thanks @milag6 for pointing out the error, and thanks @suhanaser for fixing it!
